import { VoucherViewModel } from './models/voucher-view-model';
import { UtmParametersViewModel } from './models/utm-parameters-view-model';
import { PromotionDetailsViewModel } from './models/promotion-details-view-model';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v13.19.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org) Modified by ale
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';



import { FileResponse, throwException, isAxiosError, http } from './api.client.shared';
import { environment } from '../../environment'

export interface IPromotionApiClient {
    apiPromotion(promotionId: string, utmParams: UtmParametersViewModel): Promise<PromotionDetailsViewModel>;
    apiPromotionVoucher(promotionId: string, request: UtmParametersViewModel): Promise<VoucherViewModel>;
    apiPromotionVoucherAppleWallet(promotionId: string, voucherId: string): Promise<FileResponse>;
    apiPromotionVoucherGoogleWallet(promotionId: string, voucherId: string): Promise<FileResponse>;
}


class PromotionApiClient implements IPromotionApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;


    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }





    apiPromotion(promotionId: string, utmParams: UtmParametersViewModel, cancelToken?: CancelToken | undefined): Promise<PromotionDetailsViewModel> {
        let url_ = this.baseUrl + "/api/promotion/{promotionId}";
        if (promotionId === undefined || promotionId === null)
            throw new Error("The parameter 'promotionId' must be defined.");
        url_ = url_.replace("{promotionId}", encodeURIComponent("" + promotionId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(utmParams);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Get",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetapiPromotion(_response);
        });
    }

    protected processGetapiPromotion(response: AxiosResponse): Promise<PromotionDetailsViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PromotionDetailsViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<PromotionDetailsViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PromotionDetailsViewModel>(null as any);
    }


    apiPromotionVoucher(promotionId: string, request: UtmParametersViewModel, cancelToken?: CancelToken | undefined): Promise<VoucherViewModel> {
        let url_ = this.baseUrl + "/api/promotion/{promotionId}/voucher";
        if (promotionId === undefined || promotionId === null)
            throw new Error("The parameter 'promotionId' must be defined.");
        url_ = url_.replace("{promotionId}", encodeURIComponent("" + promotionId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostapiPromotionVoucher(_response);
        });
    }

    protected processPostapiPromotionVoucher(response: AxiosResponse): Promise<VoucherViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = VoucherViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<VoucherViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<VoucherViewModel>(null as any);
    }


    apiPromotionVoucherAppleWallet(promotionId: string, voucherId: string, cancelToken?: CancelToken | undefined): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/promotion/{promotionId}/voucher/{voucherId}/apple-wallet";
        if (promotionId === undefined || promotionId === null)
            throw new Error("The parameter 'promotionId' must be defined.");
        url_ = url_.replace("{promotionId}", encodeURIComponent("" + promotionId));
        if (voucherId === undefined || voucherId === null)
            throw new Error("The parameter 'voucherId' must be defined.");
        url_ = url_.replace("{voucherId}", encodeURIComponent("" + voucherId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            responseType: "blob",
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/octet-stream"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetapiPromotionVoucherAppleWallet(_response);
        });
    }

    protected processGetapiPromotionVoucherAppleWallet(response: AxiosResponse): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers["content-disposition"] : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return Promise.resolve({ fileName: fileName, status: status, data: new Blob([response.data], { type: response.headers["content-type"] }), headers: _headers });
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<FileResponse>(null as any);
    }


    apiPromotionVoucherGoogleWallet(promotionId: string, voucherId: string, cancelToken?: CancelToken | undefined): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/promotion/{promotionId}/voucher/{voucherId}/google-wallet";
        if (promotionId === undefined || promotionId === null)
            throw new Error("The parameter 'promotionId' must be defined.");
        url_ = url_.replace("{promotionId}", encodeURIComponent("" + promotionId));
        if (voucherId === undefined || voucherId === null)
            throw new Error("The parameter 'voucherId' must be defined.");
        url_ = url_.replace("{voucherId}", encodeURIComponent("" + voucherId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            responseType: "blob",
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/octet-stream"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetapiPromotionVoucherGoogleWallet(_response);
        });
    }

    protected processGetapiPromotionVoucherGoogleWallet(response: AxiosResponse): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers["content-disposition"] : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return Promise.resolve({ fileName: fileName, status: status, data: new Blob([response.data], { type: response.headers["content-type"] }), headers: _headers });
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    protected throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        return throwException(message, status, response, headers, result);
    }
}


export const promotionApiClient = new PromotionApiClient(environment.baseUrl, http)






