import { CheckoutResponse } from './models/checkout-response';
import { CheckoutRequest } from './models/checkout-request';
import { SessionPaymentMethodViewModel } from './models/session-payment-method-view-model';
import { PaymentMethodViewModel } from './models/payment-method-view-model';
import { AddPaymentMethodRequest } from './models/add-payment-method-request';
import { WalletViewModel } from './models/wallet-view-model';
import { BaseSearchRequest } from './models/base-search-request';
import { PaginatedResultOfWalletTransactionViewModel } from './models/paginated-result-of-wallet-transaction-view-model';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v13.19.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org) Modified by ale
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';



import { FileResponse, throwException, isAxiosError, http } from './api.client.shared';
import { environment } from '../../environment'

export interface IUserPaymentApiClient {
    userpaymentMethodsPut(request: AddPaymentMethodRequest): Promise<void>;
    userpaymentMethodsGet(): Promise<PaymentMethodViewModel[]>;
    userpaymentMethodsDelete(paymentMethodId: string): Promise<void>;
    userpaymentWalletPaymentProviders(walletId: string): Promise<SessionPaymentMethodViewModel[]>;
    userpaymentWallets(): Promise<WalletViewModel[]>;
    userpaymentWallet(walletId: string): Promise<WalletViewModel>;
    userpaymentWalletTransactions(walletId: string, searchRequest: BaseSearchRequest): Promise<PaginatedResultOfWalletTransactionViewModel>;
    userpaymentWalletCharge(walletId: string, request: CheckoutRequest): Promise<CheckoutResponse>;
    userpaymentConfirmAuth(paymentProviderId: number, authCode: string): Promise<string>;
}


class UserPaymentApiClient implements IUserPaymentApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;


    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }





    userpaymentMethodsPut(request: AddPaymentMethodRequest, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/userpayment/methods";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Put",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPutuserpaymentMethodsPut(_response);
        });
    }

    protected processPutuserpaymentMethodsPut(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }


    userpaymentMethodsGet( cancelToken?: CancelToken | undefined): Promise<PaymentMethodViewModel[]> {
        let url_ = this.baseUrl + "/userpayment/methods";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetuserpaymentMethodsGet(_response);
        });
    }

    protected processGetuserpaymentMethodsGet(response: AxiosResponse): Promise<PaymentMethodViewModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PaymentMethodViewModel.fromJS(item, _mappings));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<PaymentMethodViewModel[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PaymentMethodViewModel[]>(null as any);
    }


    userpaymentMethodsDelete(paymentMethodId: string, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/userpayment/methods/{paymentMethodId}";
        if (paymentMethodId === undefined || paymentMethodId === null)
            throw new Error("The parameter 'paymentMethodId' must be defined.");
        url_ = url_.replace("{paymentMethodId}", encodeURIComponent("" + paymentMethodId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Delete",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteuserpaymentMethodsDelete(_response);
        });
    }

    protected processDeleteuserpaymentMethodsDelete(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }


    userpaymentWalletPaymentProviders(walletId: string, cancelToken?: CancelToken | undefined): Promise<SessionPaymentMethodViewModel[]> {
        let url_ = this.baseUrl + "/userpayment/wallet/{walletId}/payment-providers";
        if (walletId === undefined || walletId === null)
            throw new Error("The parameter 'walletId' must be defined.");
        url_ = url_.replace("{walletId}", encodeURIComponent("" + walletId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetuserpaymentWalletPaymentProviders(_response);
        });
    }

    protected processGetuserpaymentWalletPaymentProviders(response: AxiosResponse): Promise<SessionPaymentMethodViewModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SessionPaymentMethodViewModel.fromJS(item, _mappings));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<SessionPaymentMethodViewModel[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<SessionPaymentMethodViewModel[]>(null as any);
    }


    userpaymentWallets( cancelToken?: CancelToken | undefined): Promise<WalletViewModel[]> {
        let url_ = this.baseUrl + "/userpayment/wallets";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetuserpaymentWallets(_response);
        });
    }

    protected processGetuserpaymentWallets(response: AxiosResponse): Promise<WalletViewModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(WalletViewModel.fromJS(item, _mappings));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<WalletViewModel[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<WalletViewModel[]>(null as any);
    }


    userpaymentWallet(walletId: string, cancelToken?: CancelToken | undefined): Promise<WalletViewModel> {
        let url_ = this.baseUrl + "/userpayment/wallet/{walletId}";
        if (walletId === undefined || walletId === null)
            throw new Error("The parameter 'walletId' must be defined.");
        url_ = url_.replace("{walletId}", encodeURIComponent("" + walletId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetuserpaymentWallet(_response);
        });
    }

    protected processGetuserpaymentWallet(response: AxiosResponse): Promise<WalletViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = WalletViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<WalletViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<WalletViewModel>(null as any);
    }


    userpaymentWalletTransactions(walletId: string, searchRequest: BaseSearchRequest, cancelToken?: CancelToken | undefined): Promise<PaginatedResultOfWalletTransactionViewModel> {
        let url_ = this.baseUrl + "/userpayment/wallet/{walletId}/transactions";
        if (walletId === undefined || walletId === null)
            throw new Error("The parameter 'walletId' must be defined.");
        url_ = url_.replace("{walletId}", encodeURIComponent("" + walletId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(searchRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostuserpaymentWalletTransactions(_response);
        });
    }

    protected processPostuserpaymentWalletTransactions(response: AxiosResponse): Promise<PaginatedResultOfWalletTransactionViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PaginatedResultOfWalletTransactionViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<PaginatedResultOfWalletTransactionViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PaginatedResultOfWalletTransactionViewModel>(null as any);
    }


    userpaymentWalletCharge(walletId: string, request: CheckoutRequest, cancelToken?: CancelToken | undefined): Promise<CheckoutResponse> {
        let url_ = this.baseUrl + "/userpayment/wallet/{walletId}/charge";
        if (walletId === undefined || walletId === null)
            throw new Error("The parameter 'walletId' must be defined.");
        url_ = url_.replace("{walletId}", encodeURIComponent("" + walletId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostuserpaymentWalletCharge(_response);
        });
    }

    protected processPostuserpaymentWalletCharge(response: AxiosResponse): Promise<CheckoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = CheckoutResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<CheckoutResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CheckoutResponse>(null as any);
    }


    userpaymentConfirmAuth(paymentProviderId: number, authCode: string, cancelToken?: CancelToken | undefined): Promise<string> {
        let url_ = this.baseUrl + "/userpayment/confirm/{paymentProviderId}/auth/{authCode}";
        if (paymentProviderId === undefined || paymentProviderId === null)
            throw new Error("The parameter 'paymentProviderId' must be defined.");
        url_ = url_.replace("{paymentProviderId}", encodeURIComponent("" + paymentProviderId));
        if (authCode === undefined || authCode === null)
            throw new Error("The parameter 'authCode' must be defined.");
        url_ = url_.replace("{authCode}", encodeURIComponent("" + authCode));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Post",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostuserpaymentConfirmAuth(_response);
        });
    }

    protected processPostuserpaymentConfirmAuth(response: AxiosResponse): Promise<string> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return Promise.resolve<string>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string>(null as any);
    }

    protected throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        return throwException(message, status, response, headers, result);
    }
}


export const userPaymentApiClient = new UserPaymentApiClient(environment.baseUrl, http)






