import { OnboardingMenuImportResult } from './models/onboarding-menu-import-result';
import { OnboardingStoreInfo } from './models/onboarding-store-info';
import { OnboardingRegisterRequest } from './models/onboarding-register-request';
import { OnboardingRegisterResponse } from './models/onboarding-register-response';
import { OnboardingPaymentSetupResponse } from './models/onboarding-payment-setup-response';
import { OnboardingInitRequest } from './models/onboarding-init-request';
import { OnboardingInitResponse } from './models/onboarding-init-response';
import { GoogleBusinessLocationViewModel } from './models/google-business-location-view-model';
import { OnboardingLinkGoogleBusinessRequest } from './models/onboarding-link-google-business-request';
import { OnboardingLinkGoogleBusinessResponse } from './models/onboarding-link-google-business-response';
import { OnboardingManualStoreRequest } from './models/onboarding-manual-store-request';
import { OnboardingMediaViewModel } from './models/onboarding-media-view-model';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v13.19.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org) Modified by ale
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';



import { FileResponse, throwException, isAxiosError, http } from './api.client.shared';
import { environment } from '../../environment'

export interface IOnboardingApiClient {
    onboardingGooglePlace(placeId: string): Promise<OnboardingStoreInfo>;
    onboardingRegister(request: OnboardingRegisterRequest): Promise<OnboardingRegisterResponse>;
    onboardingMenuImportPost(storeId: string, imageBase64: string): Promise<OnboardingMenuImportResult>;
    onboardingMenuImportGet(storeId: string, operationId: string): Promise<string>;
    onboardingPaymentMethodSetup(storeId: string): Promise<OnboardingPaymentSetupResponse>;
    onboardingAccountInit(request: OnboardingInitRequest): Promise<OnboardingInitResponse>;
    onboardingGoogleBusinessToken(authCode: string): Promise<void>;
    onboardingGoogleBusinessLocations(): Promise<GoogleBusinessLocationViewModel[]>;
    onboardingGoogleBusinessLink(storeId: string, request: OnboardingLinkGoogleBusinessRequest): Promise<OnboardingLinkGoogleBusinessResponse>;
    onboardingManual(storeId: string, request: OnboardingManualStoreRequest): Promise<OnboardingLinkGoogleBusinessResponse>;
    onboardingGalleryPut(storeId: string, media: OnboardingMediaViewModel): Promise<OnboardingMediaViewModel>;
    onboardingGalleryGet(storeId: string): Promise<OnboardingMediaViewModel[]>;
    onboardingGalleryDelete(storeId: string, imageId: string): Promise<void>;
}


class OnboardingApiClient implements IOnboardingApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;


    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }





    onboardingGooglePlace(placeId: string, cancelToken?: CancelToken | undefined): Promise<OnboardingStoreInfo> {
        let url_ = this.baseUrl + "/onboarding/google-place/{placeId}";
        if (placeId === undefined || placeId === null)
            throw new Error("The parameter 'placeId' must be defined.");
        url_ = url_.replace("{placeId}", encodeURIComponent("" + placeId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetonboardingGooglePlace(_response);
        });
    }

    protected processGetonboardingGooglePlace(response: AxiosResponse): Promise<OnboardingStoreInfo> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingStoreInfo.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingStoreInfo>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingStoreInfo>(null as any);
    }


    onboardingRegister(request: OnboardingRegisterRequest, cancelToken?: CancelToken | undefined): Promise<OnboardingRegisterResponse> {
        let url_ = this.baseUrl + "/onboarding/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostonboardingRegister(_response);
        });
    }

    protected processPostonboardingRegister(response: AxiosResponse): Promise<OnboardingRegisterResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingRegisterResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingRegisterResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingRegisterResponse>(null as any);
    }


    onboardingMenuImportPost(storeId: string, imageBase64: string, cancelToken?: CancelToken | undefined): Promise<OnboardingMenuImportResult> {
        let url_ = this.baseUrl + "/onboarding/menu/import/{storeId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(imageBase64);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostonboardingMenuImportPost(_response);
        });
    }

    protected processPostonboardingMenuImportPost(response: AxiosResponse): Promise<OnboardingMenuImportResult> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingMenuImportResult.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingMenuImportResult>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingMenuImportResult>(null as any);
    }


    onboardingMenuImportGet(storeId: string, operationId: string, cancelToken?: CancelToken | undefined): Promise<string> {
        let url_ = this.baseUrl + "/onboarding/menu/import/{storeId}/{operationId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        if (operationId === undefined || operationId === null)
            throw new Error("The parameter 'operationId' must be defined.");
        url_ = url_.replace("{operationId}", encodeURIComponent("" + operationId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetonboardingMenuImportGet(_response);
        });
    }

    protected processGetonboardingMenuImportGet(response: AxiosResponse): Promise<string> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return Promise.resolve<string>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string>(null as any);
    }


    onboardingPaymentMethodSetup(storeId: string, cancelToken?: CancelToken | undefined): Promise<OnboardingPaymentSetupResponse> {
        let url_ = this.baseUrl + "/onboarding/payment-method/setup/{storeId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Post",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostonboardingPaymentMethodSetup(_response);
        });
    }

    protected processPostonboardingPaymentMethodSetup(response: AxiosResponse): Promise<OnboardingPaymentSetupResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingPaymentSetupResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingPaymentSetupResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingPaymentSetupResponse>(null as any);
    }


    onboardingAccountInit(request: OnboardingInitRequest, cancelToken?: CancelToken | undefined): Promise<OnboardingInitResponse> {
        let url_ = this.baseUrl + "/onboarding/account/init";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Put",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPutonboardingAccountInit(_response);
        });
    }

    protected processPutonboardingAccountInit(response: AxiosResponse): Promise<OnboardingInitResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingInitResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingInitResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingInitResponse>(null as any);
    }


    onboardingGoogleBusinessToken(authCode: string, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/onboarding/google-business/token";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(authCode);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Put",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPutonboardingGoogleBusinessToken(_response);
        });
    }

    protected processPutonboardingGoogleBusinessToken(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }


    onboardingGoogleBusinessLocations( cancelToken?: CancelToken | undefined): Promise<GoogleBusinessLocationViewModel[]> {
        let url_ = this.baseUrl + "/onboarding/google-business/locations";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetonboardingGoogleBusinessLocations(_response);
        });
    }

    protected processGetonboardingGoogleBusinessLocations(response: AxiosResponse): Promise<GoogleBusinessLocationViewModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GoogleBusinessLocationViewModel.fromJS(item, _mappings));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<GoogleBusinessLocationViewModel[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GoogleBusinessLocationViewModel[]>(null as any);
    }


    onboardingGoogleBusinessLink(storeId: string, request: OnboardingLinkGoogleBusinessRequest, cancelToken?: CancelToken | undefined): Promise<OnboardingLinkGoogleBusinessResponse> {
        let url_ = this.baseUrl + "/onboarding/google-business/link/{storeId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostonboardingGoogleBusinessLink(_response);
        });
    }

    protected processPostonboardingGoogleBusinessLink(response: AxiosResponse): Promise<OnboardingLinkGoogleBusinessResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingLinkGoogleBusinessResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingLinkGoogleBusinessResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingLinkGoogleBusinessResponse>(null as any);
    }


    onboardingManual(storeId: string, request: OnboardingManualStoreRequest, cancelToken?: CancelToken | undefined): Promise<OnboardingLinkGoogleBusinessResponse> {
        let url_ = this.baseUrl + "/onboarding/manual/{storeId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostonboardingManual(_response);
        });
    }

    protected processPostonboardingManual(response: AxiosResponse): Promise<OnboardingLinkGoogleBusinessResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingLinkGoogleBusinessResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingLinkGoogleBusinessResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingLinkGoogleBusinessResponse>(null as any);
    }


    onboardingGalleryPut(storeId: string, media: OnboardingMediaViewModel, cancelToken?: CancelToken | undefined): Promise<OnboardingMediaViewModel> {
        let url_ = this.baseUrl + "/onboarding/gallery/{storeId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(media);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Put",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPutonboardingGalleryPut(_response);
        });
    }

    protected processPutonboardingGalleryPut(response: AxiosResponse): Promise<OnboardingMediaViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OnboardingMediaViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<OnboardingMediaViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingMediaViewModel>(null as any);
    }


    onboardingGalleryGet(storeId: string, cancelToken?: CancelToken | undefined): Promise<OnboardingMediaViewModel[]> {
        let url_ = this.baseUrl + "/onboarding/gallery/{storeId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetonboardingGalleryGet(_response);
        });
    }

    protected processGetonboardingGalleryGet(response: AxiosResponse): Promise<OnboardingMediaViewModel[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(OnboardingMediaViewModel.fromJS(item, _mappings));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<OnboardingMediaViewModel[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OnboardingMediaViewModel[]>(null as any);
    }


    onboardingGalleryDelete(storeId: string, imageId: string, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/onboarding/gallery/{storeId}/{imageId}";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        if (imageId === undefined || imageId === null)
            throw new Error("The parameter 'imageId' must be defined.");
        url_ = url_.replace("{imageId}", encodeURIComponent("" + imageId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Delete",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteonboardingGalleryDelete(_response);
        });
    }

    protected processDeleteonboardingGalleryDelete(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    protected throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        return throwException(message, status, response, headers, result);
    }
}


export const onboardingApiClient = new OnboardingApiClient(environment.baseUrl, http)






