import { BookingRequest } from './models/booking-request';
import { BookingViewModel } from './models/booking-view-model';
import { PlaceBookingResponse } from './models/place-booking-response';
import { ReceiptViewModel } from './models/receipt-view-model';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v13.19.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org) Modified by ale
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';



import { FileResponse, throwException, isAxiosError, http } from './api.client.shared';
import { environment } from '../../environment'

export interface IBookingApiClient {
    bookingPatch(id: string, request: BookingRequest, email?: string | null | undefined): Promise<BookingViewModel>;
    bookingDelete(id: string, reason: string, email?: string | null | undefined): Promise<void>;
    bookingGet(id: string, email?: string | null | undefined): Promise<BookingViewModel>;
    bookingPut(request: BookingRequest): Promise<PlaceBookingResponse>;
    bookingReceipt(receiptId: string): Promise<ReceiptViewModel>;
}


class BookingApiClient implements IBookingApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;


    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }





    bookingPatch(id: string, request: BookingRequest, email?: string | null | undefined, cancelToken?: CancelToken | undefined): Promise<BookingViewModel> {
        let url_ = this.baseUrl + "/booking/{id}?";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (email !== undefined && email !== null)
            url_ += "email=" + encodeURIComponent("" + email) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Patch",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPatchbookingPatch(_response);
        });
    }

    protected processPatchbookingPatch(response: AxiosResponse): Promise<BookingViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BookingViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<BookingViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BookingViewModel>(null as any);
    }


    bookingDelete(id: string, reason: string, email?: string | null | undefined, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/booking/{id}?";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (email !== undefined && email !== null)
            url_ += "email=" + encodeURIComponent("" + email) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(reason);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Delete",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeletebookingDelete(_response);
        });
    }

    protected processDeletebookingDelete(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }


    bookingGet(id: string, email?: string | null | undefined, cancelToken?: CancelToken | undefined): Promise<BookingViewModel> {
        let url_ = this.baseUrl + "/booking/{id}?";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (email !== undefined && email !== null)
            url_ += "email=" + encodeURIComponent("" + email) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetbookingGet(_response);
        });
    }

    protected processGetbookingGet(response: AxiosResponse): Promise<BookingViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BookingViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<BookingViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BookingViewModel>(null as any);
    }


    bookingPut(request: BookingRequest, cancelToken?: CancelToken | undefined): Promise<PlaceBookingResponse> {
        let url_ = this.baseUrl + "/booking";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Put",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPutbookingPut(_response);
        });
    }

    protected processPutbookingPut(response: AxiosResponse): Promise<PlaceBookingResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PlaceBookingResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<PlaceBookingResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PlaceBookingResponse>(null as any);
    }


    bookingReceipt(receiptId: string, cancelToken?: CancelToken | undefined): Promise<ReceiptViewModel> {
        let url_ = this.baseUrl + "/booking/receipt/{receiptId}";
        if (receiptId === undefined || receiptId === null)
            throw new Error("The parameter 'receiptId' must be defined.");
        url_ = url_.replace("{receiptId}", encodeURIComponent("" + receiptId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetbookingReceipt(_response);
        });
    }

    protected processGetbookingReceipt(response: AxiosResponse): Promise<ReceiptViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ReceiptViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<ReceiptViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ReceiptViewModel>(null as any);
    }

    protected throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        return throwException(message, status, response, headers, result);
    }
}


export const bookingApiClient = new BookingApiClient(environment.baseUrl, http)






