import { ReviewViewModel } from './models/review-view-model';
import { StoreInfoViewModel } from './models/store-info-view-model';
import { MenuViewModel } from './models/menu-view-model';
import { StoreSearchRequest } from './models/store-search-request';
import { PaginatedResultOfStoreSearchResultItemViewModel } from './models/paginated-result-of-store-search-result-item-view-model';
import { UserLoginRequest } from './models/user-login-request';
import { ScheduleViewModel } from './models/schedule-view-model';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v13.19.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org) Modified by ale
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';



import { FileResponse, throwException, isAxiosError, http } from './api.client.shared';
import { environment } from '../../environment'

export interface IStoreApiClient {
    storeReview(request: ReviewViewModel): Promise<void>;
    storeSearch(request: StoreSearchRequest): Promise<PaginatedResultOfStoreSearchResultItemViewModel>;
    storeInfo(): Promise<StoreInfoViewModel>;
    storeMenu(): Promise<MenuViewModel>;
    storeWaiter(checkoutEmail: string): Promise<void>;
    storeLogin(request: UserLoginRequest): Promise<string>;
    storeRegister(request: UserLoginRequest): Promise<string>;
    // Owner-scope writes used by the public ServiceConfigModal to sync the
    // Para llevar / A domicilio weekly schedule (and auto-toggle the channel
    // on/off) when the store has the Guava orders module contracted. The
    // channel id is read from StoreInfoViewModel.orderChannelStatus[*].id.
    storeSchedulesPost(storeId: string, schedules: ScheduleViewModel[], orderChannelId?: string | null | undefined): Promise<void>;
    storeOrderchannelStatus(storeId: string, orderChannelId: string, isActive: boolean): Promise<void>;
}


class StoreApiClient implements IStoreApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;


    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }





    storeReview(request: ReviewViewModel, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/store/review";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Put",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPutstoreReview(_response);
        });
    }

    protected processPutstoreReview(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }


    storeSearch(request: StoreSearchRequest, cancelToken?: CancelToken | undefined): Promise<PaginatedResultOfStoreSearchResultItemViewModel> {
        let url_ = this.baseUrl + "/store/search";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPoststoreSearch(_response);
        });
    }

    protected processPoststoreSearch(response: AxiosResponse): Promise<PaginatedResultOfStoreSearchResultItemViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PaginatedResultOfStoreSearchResultItemViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<PaginatedResultOfStoreSearchResultItemViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PaginatedResultOfStoreSearchResultItemViewModel>(null as any);
    }


    storeInfo( cancelToken?: CancelToken | undefined): Promise<StoreInfoViewModel> {
        let url_ = this.baseUrl + "/store/info";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetstoreInfo(_response);
        });
    }

    protected processGetstoreInfo(response: AxiosResponse): Promise<StoreInfoViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = StoreInfoViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<StoreInfoViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<StoreInfoViewModel>(null as any);
    }


    storeMenu( cancelToken?: CancelToken | undefined): Promise<MenuViewModel> {
        let url_ = this.baseUrl + "/store/menu";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetstoreMenu(_response);
        });
    }

    protected processGetstoreMenu(response: AxiosResponse): Promise<MenuViewModel> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = MenuViewModel.fromJS(resultData200, _mappings);
            return Promise.resolve<MenuViewModel>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<MenuViewModel>(null as any);
    }


    storeWaiter(checkoutEmail: string, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/store/waiter";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(checkoutEmail);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPoststoreWaiter(_response);
        });
    }

    protected processPoststoreWaiter(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }


    storeLogin(request: UserLoginRequest, cancelToken?: CancelToken | undefined): Promise<string> {
        let url_ = this.baseUrl + "/store/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPoststoreLogin(_response);
        });
    }

    protected processPoststoreLogin(response: AxiosResponse): Promise<string> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return Promise.resolve<string>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string>(null as any);
    }


    storeRegister(request: UserLoginRequest, cancelToken?: CancelToken | undefined): Promise<string> {
        let url_ = this.baseUrl + "/store/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPoststoreRegister(_response);
        });
    }

    protected processPoststoreRegister(response: AxiosResponse): Promise<string> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return Promise.resolve<string>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string>(null as any);
    }

    // Owner-scope endpoints — ported from guavagram-admin's api.client.store
    // so the public ServiceConfigModal can sync the takeaway / delivery
    // schedule directly to the Guava platform. URLs mirror the admin client
    // 1:1 (same backend route, just exposed in the shared slim client too).
    // Requires an owner-scope session token (the same one useStoreProfilePlatformSync
    // already relies on for /platform/storeprofile/*).

    storeSchedulesPost(storeId: string, schedules: ScheduleViewModel[], orderChannelId?: string | null | undefined, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/store/{storeId}/schedules?";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        if (orderChannelId !== undefined && orderChannelId !== null)
            url_ += "orderChannelId=" + encodeURIComponent("" + orderChannelId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(schedules);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            const status = _response.status;
            if (status === 200 || status === 204) return;
            return throwException("An unexpected server error occurred.", status, _response.data, {});
        });
    }

    storeOrderchannelStatus(storeId: string, orderChannelId: string, isActive: boolean, cancelToken?: CancelToken | undefined): Promise<void> {
        let url_ = this.baseUrl + "/store/{storeId}/orderchannel/{orderChannelId}/status";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        if (orderChannelId === undefined || orderChannelId === null)
            throw new Error("The parameter 'orderChannelId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace("{orderChannelId}", encodeURIComponent("" + orderChannelId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(isActive);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Patch",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            const status = _response.status;
            if (status === 200 || status === 204) return;
            return throwException("An unexpected server error occurred.", status, _response.data, {});
        });
    }

    protected throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        return throwException(message, status, response, headers, result);
    }
}


export const storeApiClient = new StoreApiClient(environment.baseUrl, http)






