import { BillingCheckoutRequest } from './models/billing-checkout-request';
import { BillingCheckoutResponse } from './models/billing-checkout-response';
import { BillingStatusResponse } from './models/billing-status-response';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v13.19.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org) Modified by ale
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';



import { FileResponse, throwException, isAxiosError, http } from './api.client.shared';
import { environment } from '../../environment'

export interface IBillingApiClient {
    dashboardBillingCheckout(storeId: string, request: BillingCheckoutRequest): Promise<BillingCheckoutResponse>;
    dashboardBillingStatus(storeId: string): Promise<BillingStatusResponse>;
}


class BillingApiClient implements IBillingApiClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;


    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }





    dashboardBillingCheckout(storeId: string, request: BillingCheckoutRequest, cancelToken?: CancelToken | undefined): Promise<BillingCheckoutResponse> {
        let url_ = this.baseUrl + "/dashboard/{storeId}/billing/checkout";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "Post",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPostdashboardBillingCheckout(_response);
        });
    }

    protected processPostdashboardBillingCheckout(response: AxiosResponse): Promise<BillingCheckoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BillingCheckoutResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<BillingCheckoutResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BillingCheckoutResponse>(null as any);
    }


    dashboardBillingStatus(storeId: string, cancelToken?: CancelToken | undefined): Promise<BillingStatusResponse> {
        let url_ = this.baseUrl + "/dashboard/{storeId}/billing/status";
        if (storeId === undefined || storeId === null)
            throw new Error("The parameter 'storeId' must be defined.");
        url_ = url_.replace("{storeId}", encodeURIComponent("" + storeId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "Get",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetdashboardBillingStatus(_response);
        });
    }

    protected processGetdashboardBillingStatus(response: AxiosResponse): Promise<BillingStatusResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = BillingStatusResponse.fromJS(resultData200, _mappings);
            return Promise.resolve<BillingStatusResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BillingStatusResponse>(null as any);
    }

    protected throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        return throwException(message, status, response, headers, result);
    }
}


export const billingApiClient = new BillingApiClient(environment.baseUrl, http)






