import { ref, computed } from 'vue'

export type VerificationStatus = 'unverified' | 'pending' | 'verified' | 'rejected'

export interface Referral {
  id: string
  level: 1 | 2
  type: 'restaurant_recommend' | 'restaurant_claim' | 'review_claim' | 'user_invite'
  displayName: string
  avatarUrl?: string
  // Earnings generated by this referral (lifetime)
  totalGenerated: number
  // Your commission already paid out from this referral
  paidCommission: number
  // Pending commission (unpaid yet)
  pendingCommission: number
  // When it was established
  createdAt: string
  // For L2: who is the L1 bridge
  viaUserId?: string
  viaUserName?: string
}

export interface PendingClaim {
  id: string
  type: 'restaurant_added' | 'review_of_unregistered'
  restaurantName: string
  restaurantCity?: string
  createdAt: string
  // Estimated earnings if it registers
  potentialEarnings: number
  status: 'pending' | 'matched' | 'expired'
  expiresAt: string // 6 months from creation
}

export interface VoucherOption {
  restaurantId: string
  restaurantName: string
  city?: string
  logoUrl?: string
  // Discount range that can be applied (restaurant configured)
  minDiscountPct: number // e.g. 5
  maxDiscountPct: number // e.g. 100
}

export interface EarningHistoryEntry {
  id: string
  date: string
  kind: 'commission_l1' | 'commission_l2' | 'claim_bonus' | 'withdrawal' | 'voucher_conversion' | 'expired'
  amount: number // positive = credit, negative = debit
  description: string
  relatedId?: string
}

// Commission rates
export const L1_COMMISSION_PCT = 20
export const L2_COMMISSION_PCT = 10

// Verification grace period in days from first unlocked credit
const VERIFICATION_GRACE_DAYS = 90
// Credit expiration pace after grace
const EXPIRATION_MONTHS = 3 // 1/3 per month after grace ends

// ─── Module-level state (singleton) ───
const verificationStatus = ref<VerificationStatus>('unverified')
// ISO date when user first earned unlockable balance (dev mock: 25 days ago → 65 days left of grace)
const firstUnlockedAt = ref<string | null>(new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString())

const referrals = ref<Referral[]>([
  { id: 'ref-1', level: 1, type: 'restaurant_recommend', displayName: 'El Rincón de Marta', totalGenerated: 180, paidCommission: 0, pendingCommission: 36, createdAt: '2026-02-12' },
  { id: 'ref-2', level: 1, type: 'restaurant_recommend', displayName: 'Taberna La Curva', totalGenerated: 95, paidCommission: 0, pendingCommission: 19, createdAt: '2026-03-01' },
  { id: 'ref-3', level: 1, type: 'user_invite', displayName: '@lauraf', avatarUrl: '', totalGenerated: 0, paidCommission: 0, pendingCommission: 0, createdAt: '2026-03-18' },
  { id: 'ref-4', level: 2, type: 'restaurant_recommend', displayName: 'Pizzería Nonna', totalGenerated: 240, paidCommission: 0, pendingCommission: 24, createdAt: '2026-03-25', viaUserId: 'u-laura', viaUserName: '@lauraf' },
])

const pendingClaims = ref<PendingClaim[]>([
  { id: 'pc-1', type: 'restaurant_added', restaurantName: 'Bar Pepito', restaurantCity: 'Barcelona', createdAt: '2026-02-20', potentialEarnings: 20, status: 'pending', expiresAt: '2026-08-20' },
  { id: 'pc-2', type: 'review_of_unregistered', restaurantName: 'Casa Lola', restaurantCity: 'Madrid', createdAt: '2026-03-10', potentialEarnings: 25, status: 'pending', expiresAt: '2026-09-10' },
])

const earningsHistory = ref<EarningHistoryEntry[]>([
  { id: 'h-1', date: '2026-04-01', kind: 'commission_l1', amount: 15, description: 'Comisión 20% — El Rincón de Marta', relatedId: 'ref-1' },
  { id: 'h-2', date: '2026-04-05', kind: 'commission_l1', amount: 21, description: 'Comisión 20% — El Rincón de Marta', relatedId: 'ref-1' },
  { id: 'h-3', date: '2026-04-10', kind: 'commission_l2', amount: 24, description: 'Comisión 10% vía @lauraf — Pizzería Nonna', relatedId: 'ref-4' },
  { id: 'h-4', date: '2026-04-15', kind: 'commission_l1', amount: 19, description: 'Comisión 20% — Taberna La Curva', relatedId: 'ref-2' },
])

export function useCreatorWallet() {
  // ─── Computed balances ───
  const pendingBalance = computed(() =>
    referrals.value.reduce((sum, r) => sum + r.pendingCommission, 0)
  )
  const paidBalance = computed(() =>
    referrals.value.reduce((sum, r) => sum + r.paidCommission, 0)
  )
  // Balance unlockable: commissions confirmed but require verification to withdraw as cash
  const unlockableBalance = computed(() =>
    earningsHistory.value.reduce((sum, e) => {
      if (e.kind === 'commission_l1' || e.kind === 'commission_l2' || e.kind === 'claim_bonus') return sum + e.amount
      if (e.kind === 'withdrawal' || e.kind === 'voucher_conversion' || e.kind === 'expired') return sum + e.amount
      return sum
    }, 0)
  )

  const potentialFromClaims = computed(() =>
    pendingClaims.value.filter(c => c.status === 'pending').reduce((sum, c) => sum + c.potentialEarnings, 0)
  )

  const l1Referrals = computed(() => referrals.value.filter(r => r.level === 1))
  const l2Referrals = computed(() => referrals.value.filter(r => r.level === 2))

  const isVerified = computed(() => verificationStatus.value === 'verified')
  const canWithdrawCash = computed(() => isVerified.value && unlockableBalance.value > 0)

  // Grace period: deadline to verify before credits start expiring
  const verificationDeadline = computed<string | null>(() => {
    if (!firstUnlockedAt.value) return null
    const d = new Date(firstUnlockedAt.value)
    d.setDate(d.getDate() + VERIFICATION_GRACE_DAYS)
    return d.toISOString()
  })

  const daysUntilVerificationDeadline = computed<number | null>(() => {
    if (!verificationDeadline.value) return null
    const diff = new Date(verificationDeadline.value).getTime() - Date.now()
    return Math.ceil(diff / (1000 * 60 * 60 * 24))
  })

  const isGracePeriodExpired = computed(() =>
    daysUntilVerificationDeadline.value !== null && daysUntilVerificationDeadline.value < 0
  )

  // ─── Actions (mock) ───
  const startVerification = () => { verificationStatus.value = 'pending' }
  const completeVerification = () => { verificationStatus.value = 'verified' }

  const convertToVoucher = (amount: number, restaurantId: string, discountPct: number) => {
    if (amount > unlockableBalance.value) return false
    earningsHistory.value.unshift({
      id: `h-${Date.now()}`,
      date: new Date().toISOString().split('T')[0]!,
      kind: 'voucher_conversion',
      amount: -amount,
      description: `Convertido a voucher ${discountPct}% — restaurante ${restaurantId}`,
    })
    return true
  }

  const requestWithdrawal = (amount: number) => {
    if (!canWithdrawCash.value || amount > unlockableBalance.value) return false
    earningsHistory.value.unshift({
      id: `h-${Date.now()}`,
      date: new Date().toISOString().split('T')[0]!,
      kind: 'withdrawal',
      amount: -amount,
      description: `Retiro a cuenta bancaria`,
    })
    return true
  }

  return {
    // state
    verificationStatus,
    referrals,
    pendingClaims,
    earningsHistory,
    firstUnlockedAt,
    // computed
    pendingBalance,
    paidBalance,
    unlockableBalance,
    potentialFromClaims,
    l1Referrals,
    l2Referrals,
    isVerified,
    canWithdrawCash,
    verificationDeadline,
    daysUntilVerificationDeadline,
    isGracePeriodExpired,
    // actions
    startVerification,
    completeVerification,
    convertToVoucher,
    requestWithdrawal,
    // constants
    L1_COMMISSION_PCT,
    L2_COMMISSION_PCT,
    VERIFICATION_GRACE_DAYS,
  }
}
