
export enum CatalogLabelTypeEnum {
    New = 1,
    Recommended = 2,
    Nuts = 3,
    Spicy = 4,
    Vegetarian = 5,
    Gluten = 6,
    RawMeat = 7,
    RawFish = 8,
    Seafood = 9,
    Shellfish = 10,
    Eggs = 11,
    Soy = 12,
    Wheat = 13,
    Peanuts = 14,
    Sesame = 15,
    Lactose = 16,
    Alcohol = 17,
    LowCal = 18,
    Vegan = 19,
    Mustard = 20,
    Sulphites = 21,
    Celery = 22,
    Lupine = 23,
    Molluscs = 24,
    Crustaceans = 25,
    Fish = 26,
    Meat = 27,
    Poultry = 28,
    Pork = 29,
    Milk = 30,
    Cheese = 31,
    Mushrooms = 32,
}

