
export enum InventoryProductMeasureUnitTypeEnum {
    Unit = 1,
    Kilograms = 2,
    Grams = 3,
    Milligrams = 4,
    Litres = 5,
    Centilitres = 6,
    Millilitres = 7,
    Ounce = 8,
    Pound = 9,
    Box = 10,
    Can = 11,
    Bottle = 12,
    Package = 13,
    Piece = 14,
    Bag = 15,
    Barrel = 16,
    Crate = 17,
    Gallon = 18,
    Jar = 19,
    Pallet = 20,
    Roll = 21,
    Tube = 22,
    Pint = 23,
    Quart = 24,
    Portion = 25,
    Slice = 26,
    Cup = 27,
    Tablespoon = 28,
    Teaspoon = 29,
    Other = 30,
    Meter = 31,
}

