
export enum NotificationTypeEnum {
    ORDER_UPDATE = 1,
    TRANSACTION_UPDATE = 2,
    ORDERS_ACCOUNT_UPDATE = 3,
    ORDERS_ACCOUNT_JOIN_REQUEST = 4,
    BOOKING_CREATE = 5,
    BOOKING_UPDATE = 6,
    CAMPAIGN_PROMOTION = 7,
    ACTION_REWARD = 8,
    FRIEND_REQUEST = 9,
    BOOKING_REMINDER = 10,
    REVIEW_REQUEST = 11,
    STORE_MESSAGE = 12,
    SUPPLIER_MESSAGE = 13,
    SUPPLIER_ORDER_UPDATE = 14,
    ORDER_CREATE = 15,
    CASHTAKING_CLOSE = 16,
}

