
export enum PaymentProviderEnum {
    Cash = 1,
    Stripe = 2,
    Wallet = 3,
    CoinGate = 4,
    RoomCharge = 5,
    PayComet = 6,
    Checkout = 7,
    PhysicalCard = 8,
    Bank = 9,
    CustomerAccount = 10,
    UserWallet = 11,
    TemporaryStoreAccount = 12,
    Tickets = 13,
    Nexi = 14,
    External = 15,
    Glovo = 16,
    UberEats = 17,
    Deliveroo = 18,
    JustEat = 19,
    Watson = 20,
    Cashmatic = 21,
    Dojo = 22,
    Bizum = 23,
    TheForkPay = 24,
    Satispay = 25,
    TooGoodToGo = 26,
    ExternalSecondary = 27,
    Glory = 28,
    Cashlogy = 29,
    CashDro = 30,
}

